### ISSUE TITLE
Write/Load the chosen parameters to/from the log file: "watch_log.txt"

### ISSUE THREAD

**Issue by ames0k0** [alpha-hexor/animeflix#1]
Load the last one at least...
First creates a log and then streams/downloads the anime ?! - It's not "already watched/downloaded"

#### Text log file example
```
# separator, delimiter = ','
url, name, stream, episodes, streaming_episode, **other_params
```

#### Json log file example
```JSON
{
    "url": "://",
    "name": "...",
    "type": "stream",
    "episodes": [1,9],
    "streaming_episode": 4,
    "__other_params__"
}

// Or
{
    "://": {
        "name": "...",
        "type": "stream",
        "episodes": [1,9],
        "streaming_episode": 4,
        "__other_params__"
    }
}
```

### NOTE: educational purposes only

**Comment by alpha-hexor** [comment]
good idea 
we  can take config files like that as user input and do operation based on the config file.

**Comment by ames0k0** [comment]
Good luck!

I can't watch the whole season in one breath, I just wanna be able to continue watching wherever I quit
Some web sites identify you (by session/IP) and show the "Continue" button

You did a good job! But I'm too lazy :)
